name: 🔨 Release Test

on:
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
      - '**.yml'
  workflow_dispatch:

jobs:
  release-test-mac:
    runs-on: macos-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: release test
        uses: goreleaser/goreleaser-action@v4
        with:
          args: "release --clean --snapshot -f .goreleaser/mac.yml"
          version: latest
          workdir: .

  release-test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x


      - name: release test
        uses: goreleaser/goreleaser-action@v4
        with:
          args: "release --clean --snapshot -f .goreleaser/linux.yml"
          version: latest
          workdir: .

  release-test-windows:
    runs-on: windows-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: release test
        uses: goreleaser/goreleaser-action@v4
        with:
          args: "release --clean --snapshot -f .goreleaser/windows.yml"
          version: latest
          workdir: .